apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-d
  labels:
    estado: "1"
spec:
  selector:
    matchLabels:
      app: web
  replicas: 2
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: apache
        image: jhordan01/web1-apache
        ports:
        - containerPort: 80
