apiVersion: v1
kind: Pod
metadata:
  name: tomcat1
  namespace: udemy-k8s
  labels:
    estado: 'dev'
spec:
  containers:
    - name: tomcat
      image: tomcat
      ports:
        - containerPort: 8080
