apiVersion: v1
kind: Pod
metadata:
  name: tomcat4
  namespace: udemy-k8s
  labels:
    estado: 'produccion'
    responsable: 'pedro'
  annotations:
    doc: "Se debe compilar con gcc"
    adjunto: "Ejemplo de anotación"
spec:
  containers:
    - name: tomcat
      image: tomcat
